### ISSUE TITLE
Django login page error

### ISSUE THREAD

**Issue by georgetam** [metabase/embedding-reference-apps#18]
After I click enter on the django login page I am getting the error below. Any idea why? I cloned the repo and ran the manage.py as is did not edit anything. 
![django](https://user-images.githubusercontent.com/7408443/73914610-7e40cd80-486e-11ea-83a9-5c3f7469ab4e.png)

**Comment by georgetam** [comment]
resolved, the iframe url in user_stats/views.py needs to be updated. Needs token.decode("utf8") instead of just token.

**Comment by flamber** [comment]
I'm just going to keep this open, since the we should get that fixed. Thank you for the hint!
